language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - sudo apt-get -qq install libevent-dev
  - sh -c " if [ \"\$(php --re libevent | grep 'does not exist')\" != '' ]; then
              wget http://pecl.php.net/get/libevent-0.1.0.tgz;
              tar -xzf libevent-0.1.0.tgz;
              cd libevent-0.1.0 && phpize && ./configure && make && sudo make install;
              echo "extension=libevent.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`;
            fi"
  - php -i | grep "libevent version"
  - php --re libevent | grep Extension
  - composer self-update
  - composer install --dev --prefer-source

script: pu(){ phpunit --configuration phpunit.xml.dist --group="$1";echo;echo;} && pu unit && pu timeout && pu thread && pu pool
